site_name: Slim Framework v2
pages:
- Home: index.md
- Get Started: start/get-started.md
- Configuration:
  - Overview: configuration/overview.md
  - Settings: configuration/settings.md
  - Names and Scopes: configuration/names-and-scopes.md
  - Modes: configuration/modes.md
- Routing:
  - Overview: routing/overview.md
  - GET Routes: routing/get.md
  - POST Routes: routing/post.md
  - PUT Routes: routing/put.md
  - DELETE Routes: routing/delete.md
  - OPTIONS Routes: routing/options.md
  - PATCH Routes: routing/patch.md
  - Custom Routes: routing/custom.md
  - Parameters: routing/params.md
  - Names: routing/names.md
  - Conditions: routing/conditions.md
  - Middleware: routing/middleware.md
  - Groups: routing/groups.md
  - Helpers: routing/helpers.md
  - URL Rewriting: routing/rewrite.md
- Environment:
  - Overview: environment/overview.md
- Request:
  - Overview: request/overview.md
  - Method: request/method.md
  - Headers: request/headers.md
  - Body: request/body.md
  - Variables: request/variables.md
  - Cookies: request/cookies.md
  - Paths: request/paths.md
  - XHR: request/xhr.md
  - Helpers: request/helpers.md
  - Content-Types: request/content-types.md
- Response:
  - Overview: response/overview.md
  - Status: response/status.md
  - Headers: response/headers.md
  - Body: response/body.md
  - Cookies: response/cookies.md
  - Helpers: response/helpers.md
- View:
  - Overview: view/overview.md
  - Rendering: view/rendering.md
  - Custom: view/custom.md
  - Data: view/data.md
- HTTP Cache:
  - Overview: cache/overview.md
  - ETag: cache/etag.md
  - Last Modified: cache/lastmodified.md
  - Expires: cache/expires.md
- Middleware:
  - Overview: middleware/overview.md
  - How to Use: middleware/how-to-use.md
  - How to Write: middleware/how-to-write.md
- Hooks:
  - Overview: hooks/overview.md
  - How to Use: hooks/how-to-use.md
  - Defaults: hooks/defaults.md
  - Custom: hooks/custom.md
- Flash Messages:
  - Overview: flash/overview.md
  - Next: flash/next.md
  - Now: flash/now.md
  - Keep: flash/keep.md
- Sessions:
  - Native: sessions/native.md
  - Cookies: sessions/cookies.md
- Logging:
  - Activate: logging/activate.md
  - Levels: logging/levels.md
  - Writers: logging/writers.md
- Error Handling:
  - Overview: errors/overview.md
  - 500 System Error: errors/500.md
  - 404 Not Found: errors/404.md
  - Debug Mode: errors/debug.md
  - Output: errors/output.md
- Dependency Injection:
  - Overview: di/overview.md
theme: readthedocs
markdown_extensions: [markdown.extensions.extra]
